FROM node:20-slim AS base

ARG NEXT_PUBLIC_SANITY_DATASET
ARG SENDGRID_TEMPLATE_ID
ARG SENDGRID_TEMPLATE_CONFIRMATION
ARG SENDGRID_REPLY_TO
ARG SENDGRID_FROM_EMAIL
ARG SENDGRID_FROM_NAME
ENV NEXT_PUBLIC_SANITY_DATASET=$NEXT_PUBLIC_SANITY_DATASET
ENV SENDGRID_TEMPLATE_ID=$SENDGRID_TEMPLATE_ID
ENV SENDGRID_TEMPLATE_CONFIRMATION=$SENDGRID_TEMPLATE_CONFIRMATION
ENV SENDGRID_REPLY_TO=$SENDGRID_REPLY_TO
ENV SENDGRID_FROM_EMAIL=$SENDGRID_FROM_EMAIL
ENV SENDGRID_FROM_NAME=$SENDGRID_FROM_NAME

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN --mount=type=secret,id=SENDGRID_API_KEY,env=SENDGRID_API_KEY \
    --mount=type=secret,id=TURNSTILE_SECRET,env=TURNSTILE_SECRET \
    --mount=type=secret,id=NEXT_PUBLIC_SANITY_PROJECT_ID,env=NEXT_PUBLIC_SANITY_PROJECT_ID \
    --mount=type=secret,id=NEXT_PUBLIC_TURNSTILE_SITE_KEY,env=NEXT_PUBLIC_TURNSTILE_SITE_KEY \
    pnpm run build

FROM base
COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
EXPOSE 8000
CMD [ "pnpm", "start" ]